## Chap.11 예외 처리

### 예외와 예외 클래스

- **일반 예외 (Exception) :** 컴파일러가 예외 코드 여부를 검사하는 예외
- **실행 예외 (Runtime Exception) :** 컴파일러가 예외 처리 코드 여부를 검사하지 않는 예외

---

### 예외 처리 코드

```java
try {
	...
} catch (예외클래스 e) {
 ...
} finally {
 //항상 실행하는 부분
}
```

```java
public static void main(String[] args) {
	System.out.println("프로그램 시작");
	printLength("ThisIsJava");
	printLength(null);
	System.out.println("프로그램 종료");
}

public void printLength(String data) {
	int result = data.length();
	System.out.println("문자 수 : " + result);
}
/*실행 결과 :
프로그램 시작
문자 수 : 10
NullPointerException~~~
```

- `printLength()` 에서 `data`에 `null` 값이 들어와 `NullPointerException` 발생
- `“프로그램 종료”` 가 출력되지 않음

```java
public static void main(String[] args) {
	System.out.println("프로그램 시작");
	printLength("ThisIsJava");
	printLength(null);
	System.out.println("프로그램 종료");
}

public void printLength(String data) {
	try {
		int result = data.length();
		System.out.println("문자 수 : " + result);
	} catch (NullPointerException e) {
			System.out.println(e.getMessage());
	} finally {
			System.out.println("마무리 실행\n");
	}
}
/* 실행 결과 :
프로그램 시작
문자 수 : 10
Cannot invoke "String.length()" because "data" is Null
마무리 실행

프로그램 종료
```

- `e.getMessage()` : 예외가 발생한 이유만 리턴
- `e.toString()` : 예외의 종류 또한 리턴
- `e.printStackTrace()` : 예외의 발생 위치 리턴
